//! Event definitions and streaming infrastructure for Noema.
//!
//! Events describe everything that happens inside a Noema runtime: session
//! lifecycle, routing, model activity, tool execution, approvals, memory,
//! escalation, and errors.
//!
//! The frontend subscribes to an [`EventStream`] and reacts to events as they
//! arrive. It never polls for agent state.

use std::fmt;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};
use tokio::sync::broadcast;

/// A unique identifier for a Noema session.
///
/// Session ids are generated by the runtime and are unique within a process.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SessionId(String);

static SESSION_COUNTER: AtomicU64 = AtomicU64::new(0);

impl SessionId {
    /// Generates a new, unique session id.
    pub fn generate() -> Self {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let counter = SESSION_COUNTER.fetch_add(1, Ordering::Relaxed);
        SessionId(format!("{nanos:020x}{counter:016x}"))
    }

    /// The raw string form of the id.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for SessionId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// Every event emitted by a Noema runtime.
///
/// The variant set is deliberately complete from the start: consumers can
/// rely on the full vocabulary even while later milestones fill in the
/// behaviour that produces each event.
#[derive(Debug, Clone, PartialEq, Serialize)]
pub enum Event {
    /// A session was created.
    SessionStarted { session_id: SessionId },
    /// A user message was received by the runtime.
    UserMessageReceived { session_id: SessionId },
    /// Initial text routing began.
    RoutingStarted { session_id: SessionId },
    /// Initial text routing completed with a handled action.
    RoutingCompleted { session_id: SessionId },
    /// Initial text routing escalated the request to Gemma.
    RoutingEscalated { session_id: SessionId },
    /// A model began generating.
    ModelStarted { session_id: SessionId, model: String },
    /// A streaming delta from a model.
    ModelDelta { session_id: SessionId, delta: String },
    /// A model finished generating.
    ModelCompleted { session_id: SessionId },
    /// Gemma issued a semantic tool request.
    ToolRequested { session_id: SessionId },
    /// A tool request was formatted into a structured call by Needle.
    ToolFormatted { session_id: SessionId },
    /// A tool call requires human approval.
    ToolApprovalRequired { session_id: SessionId },
    /// A pending tool approval was approved.
    ToolApproved { session_id: SessionId },
    /// A pending tool approval was rejected.
    ToolRejected { session_id: SessionId },
    /// A tool began executing.
    ToolStarted { session_id: SessionId },
    /// Progress from a long-running tool.
    ToolProgress { session_id: SessionId },
    /// A tool finished executing successfully.
    ToolCompleted { session_id: SessionId },
    /// A tool failed.
    ToolFailed { session_id: SessionId },
    /// Relevant memories were retrieved from Mnemo.
    MemoryRetrieved { session_id: SessionId },
    /// Memories were written to Mnemo.
    MemoryWritten { session_id: SessionId },
    /// A task began escalating to a larger model.
    EscalationStarted { session_id: SessionId },
    /// An escalation finished.
    EscalationCompleted { session_id: SessionId },
    /// The assistant began producing its final response.
    AssistantStarted { session_id: SessionId },
    /// A streaming delta of the assistant's response.
    AssistantDelta { session_id: SessionId, delta: String },
    /// The assistant finished its response.
    AssistantCompleted { session_id: SessionId },
    /// An error occurred within the session.
    Error { session_id: SessionId, error: String },
    /// The session was closed.
    SessionCompleted { session_id: SessionId },
}

impl Event {
    /// The session this event belongs to.
    pub fn session_id(&self) -> Option<&SessionId> {
        Some(match self {
            Event::SessionStarted { session_id } => session_id,
            Event::UserMessageReceived { session_id } => session_id,
            Event::RoutingStarted { session_id } => session_id,
            Event::RoutingCompleted { session_id } => session_id,
            Event::RoutingEscalated { session_id } => session_id,
            Event::ModelStarted { session_id, .. } => session_id,
            Event::ModelDelta { session_id, .. } => session_id,
            Event::ModelCompleted { session_id } => session_id,
            Event::ToolRequested { session_id } => session_id,
            Event::ToolFormatted { session_id } => session_id,
            Event::ToolApprovalRequired { session_id } => session_id,
            Event::ToolApproved { session_id } => session_id,
            Event::ToolRejected { session_id } => session_id,
            Event::ToolStarted { session_id } => session_id,
            Event::ToolProgress { session_id } => session_id,
            Event::ToolCompleted { session_id } => session_id,
            Event::ToolFailed { session_id } => session_id,
            Event::MemoryRetrieved { session_id } => session_id,
            Event::MemoryWritten { session_id } => session_id,
            Event::EscalationStarted { session_id } => session_id,
            Event::EscalationCompleted { session_id } => session_id,
            Event::AssistantStarted { session_id } => session_id,
            Event::AssistantDelta { session_id, .. } => session_id,
            Event::AssistantCompleted { session_id } => session_id,
            Event::Error { session_id, .. } => session_id,
            Event::SessionCompleted { session_id } => session_id,
        })
    }
}

/// A broadcast bus for [`Event`]s.
///
/// Multiple subscribers can attach; each published event is delivered to
/// every subscriber that was attached at publish time.
#[derive(Clone, Debug)]
pub struct EventBus {
    tx: broadcast::Sender<Event>,
}

impl EventBus {
    /// Creates a bus with the given channel capacity.
    ///
    /// If a subscriber falls behind the capacity, it skips ahead to the
    /// latest events (see [`EventStream::next`]).
    pub fn new(capacity: usize) -> Self {
        let (tx, _) = broadcast::channel(capacity);
        Self { tx }
    }

    /// Publishes an event to all current subscribers.
    ///
    /// A send only fails when there are no receivers left; for a bus with
    /// transient subscribers that is not an error.
    pub fn publish(&self, event: Event) {
        let _ = self.tx.send(event);
    }

    /// Subscribes to every event on the bus.
    pub fn subscribe_all(&self) -> EventStream {
        EventStream {
            rx: self.tx.subscribe(),
            filter: None,
        }
    }

    /// Subscribes to the events of a single session.
    pub fn subscribe(&self, session_id: SessionId) -> EventStream {
        EventStream {
            rx: self.tx.subscribe(),
            filter: Some(session_id),
        }
    }
}

impl Default for EventBus {
    fn default() -> Self {
        Self::new(1024)
    }
}

/// A stream of [`Event`]s received from an [`EventBus`].
#[derive(Debug)]
pub struct EventStream {
    rx: broadcast::Receiver<Event>,
    filter: Option<SessionId>,
}

impl EventStream {
    /// Returns the next event, or `None` once the bus has been closed.
    ///
    /// When filtered to a session, events from other sessions are skipped.
    pub async fn next(&mut self) -> Option<Event> {
        loop {
            match self.rx.recv().await {
                Ok(event) => {
                    if let Some(expected) = &self.filter {
                        if event.session_id() != Some(expected) {
                            continue;
                        }
                    }
                    return Some(event);
                }
                Err(broadcast::error::RecvError::Closed) => return None,
                // The subscriber fell behind; skip ahead to the latest events.
                Err(broadcast::error::RecvError::Lagged(_)) => continue,
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn session_ids_are_unique() {
        let a = SessionId::generate();
        let b = SessionId::generate();
        assert_ne!(a, b);
        assert!(!a.as_str().is_empty());
    }

    #[test]
    fn events_carry_their_session() {
        let id = SessionId::generate();
        let event = Event::SessionStarted { session_id: id.clone() };
        assert_eq!(event.session_id(), Some(&id));
    }

    #[tokio::test]
    async fn bus_delivers_to_all_subscribers() {
        let bus = EventBus::new(16);
        let mut one = bus.subscribe_all();
        let mut two = bus.subscribe_all();
        let id = SessionId::generate();

        bus.publish(Event::SessionStarted { session_id: id.clone() });

        assert_eq!(
            one.next().await,
            Some(Event::SessionStarted { session_id: id.clone() })
        );
        assert_eq!(two.next().await, Some(Event::SessionStarted { session_id: id }));
    }

    #[tokio::test]
    async fn session_filter_skips_other_sessions() {
        let bus = EventBus::new(16);
        let a = SessionId::generate();
        let b = SessionId::generate();
        let mut stream = bus.subscribe(b.clone());

        bus.publish(Event::SessionStarted { session_id: a });
        bus.publish(Event::SessionCompleted { session_id: b.clone() });

        assert_eq!(
            stream.next().await,
            Some(Event::SessionCompleted { session_id: b })
        );
    }
}
